[Database]
dbms = "mysql"
server = "mysql"
port =  "3306"
database = "goexample"
parseTime = "true"
user = "admin"
password = "admin"
LogMode = true
MaxIdleConnections = 3
MaxOpenConnections = 3
MaxLifetime = 60 #秒単位で設定

[Message]
E0001="不正なパラメータです。"

[Log]
Level="DEBUG"
LogHeader="${time_rfc3339} ${level}:"
Mask=["username","password","email","phoneno","name_family","name_given","memo"]

[TestDatabase]
dbms = "mysql"
server = "mysql"
port =  "3306"
database = "goexample-test"
parseTime = "true"
user = "admin"
password = "admin"
LogMode = false
MaxIdleConnections = 3
MaxOpenConnections = 3
MaxLifetime = 60 #秒単位で設定

[Request]
authHeaderKey="X-Authorization"
deviceKey="Device"
versionKey="Version"

[Response]
updateRequiredKey = "Update-Required"

[Authorization]
secret="AUTHORIZATION_SECRET" #環境変数名
expired=86400
